# Maven Build on Windows Agent
# Uses Azure DevOps Free Tier with windows-latest VM
# Builds Java project and runs tests using Maven

trigger:
- main

pool:
  vmImage: 'windows-latest'  # Change from 'ubuntu-latest' to 'windows-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'verify'
